package com.e2e.construction.entity;

public enum NotificationType {
    LABOR_WORK_REQUEST,
    LABOR_REQUEST_ACCEPTANCE,
    LABOR_REQUEST_REJECTION,
    MACHINERY_BOOKING_REQUEST,
    MACHINERY_BOOKING_ACCEPTANCE,
    MACHINERY_BOOKING_REJECTION,
    MATERIAL_ORDER,
    MATERIAL_ORDER_ACCEPTANCE,
    MATERIAL_ORDER_REJECTION,
    TENDER_UPDATE,
    ADMIN_VERIFICATION,
    PROJECT_UPDATE
}
